spring:
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
jwt:
  http-header: Authorization
  token-prefix: Bearer
  token-lifetime: 300000
  signing-key: 5ab88be4-676f-4ce1-ac8b-f1d838b4ae83
debug: false
